const REQ_TRANSACTION_LIST = 'REQ_TRANSACTION_LIST';
const REQ_TRANSACTION_LIST_SUCCESS = 'REQ_TRANSACTION_LIST_SUCCESS';
const REQ_TRANSACTION_LIST_FAILED = 'REQ_TRANSACTION_LIST_FAILED';

export {
  REQ_TRANSACTION_LIST,
  REQ_TRANSACTION_LIST_SUCCESS,
  REQ_TRANSACTION_LIST_FAILED,
};
